spring:
  application:
    name: order_processing_service
  cloud:
    kubernetes:
      secrets:
        name: order-processing-secret
        namespace: default
        enabled: true
        enableApi: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
#    url: jdbc:mysql://localhost:3306/my-k8s-demo-db
    url: jdbc:mysql://${HOST}/${DATABASE}
    username: ${USER}
    password: ${MYSQL_ROOT_PASSWORD}
  rabbitmq:
    host: rabbitmq-service
    username: ${RABBIT}
    password: ${RABBIT_PWD}
