apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-services-global
subjects:
- kind: ServiceAccount
  name: default 
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: services-reader
  apiGroup: rbac.authorization.k8s.io
