# Config initDB
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `my-k8s-demo-db`;
    USE `my-k8s-demo-db`;
    CREATE TABLE  user (id INT NOT NULL AUTO_INCREMENT,first_name VARCHAR(100) NOT NULL,last_name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,password VARCHAR(45) NOT NULL,role VARCHAR(45) NOT NULL,PRIMARY KEY (id),UNIQUE INDEX email_UNIQUE (email ASC) VISIBLE); 
    
    CREATE TABLE  orders (id INT NOT NULL AUTO_INCREMENT,user_id INT NULL,PRIMARY KEY (id),INDEX fk_user_id_idx (user_id ASC) VISIBLE,CONSTRAINT fk_user_id  FOREIGN KEY (user_id)  REFERENCES user (id)  ON DELETE CASCADE  ON UPDATE CASCADE);

    CREATE TABLE  product (id INT NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,price DECIMAL(6,2) NOT NULL,quantity_in_stock INT NOT NULL,PRIMARY KEY (id));

    CREATE TABLE  order_item (id INT NOT NULL AUTO_INCREMENT,order_id INT NOT NULL,product_id INT NOT NULL,quantity INT NOT NULL,PRIMARY KEY (id),INDEX fk_order_id_idx (order_id ASC) VISIBLE,INDEX fk_product_id_idx (product_id ASC) VISIBLE,CONSTRAINT fk_order_id  FOREIGN KEY (order_id)  REFERENCES orders (id)  ON DELETE CASCADE  ON UPDATE CASCADE,CONSTRAINT fk_product_id  FOREIGN KEY (product_id)  REFERENCES product (id)  ON DELETE CASCADE  ON UPDATE CASCADE);

    INSERT INTO product (name,price,quantity_in_stock) VALUES ('item1', 10.50, 100);
    INSERT INTO product (name,price,quantity_in_stock) VALUES ('item2', 9.75, 150);
    INSERT INTO product (name,price,quantity_in_stock) VALUES ('item3', 15.35, 180);